### ISSUE TITLE
Sky background subtraction for LSB science section

### ISSUE THREAD

**Issue by brantr** [brantr/ExtragalacticScienceRoadmap#1]
From Johan Knapen:

There is evidence that all of the deep surveys (including KiDS, CFHT Virgo cluster, new Subaru data that was released recently) do this wrong, by oversubtracting the sky background. This is a natural occurrence of optimising the process for the detection of (high-redshift) point sources, but it kills the LSB science. I think you can see this in e.g. Fig 2 of http://adsabs.harvard.edu/abs/2017arXiv170701904H where both the PSF and the galaxy light profiles drop off steeply at a relatively bright level of 28. This can hardly be real, and is oversubtraction in action. At the moment, in Section 3.6 on LSB science, I think this is only implicit in point e) of the activities of 3.6.1, where we say we need to ensure that the L2 strategies are aligned with the needs of LSB science. I think we need to be more explicit and specifically mention the potential stress between background subtraction strategies optimised for faint point source detection, and for faint extended structure detection.

**Comment by brantr** [comment]
Section written by Tony Tyson, to be integrated.
[skysub-task.tex.txt](https://github.com/brantr/ExtragalacticScienceRoadmap/files/1191093/skysub-task.tex.txt)

**Comment by sschmidt23** [comment]
minor typos:
surace -> surface
mag/sq.arcsec -> mag/sq.\~arcsec
stalight -> starlight
gaussian -> Gaussian
successul -> successful
charaterization -> characterization

Deliverable 1 references the DESC SRM DC1 simulations, this should be laid out more explicitly (and should refer to DC2, since DC1 simulations are already finished)
I would add text referencing DESC and DC2 in the activities section and modify Deliverabl 1 with the below text (@brantr, I will email you a file separately with the typo corrections and below text in case that's easier to deal with).

LSST data management are planning novel algorithms of this general sort, and close coordination will be necessary and beneficial.  The Dark Energy Science Collaboration (DESC) Science Roadmap\footnote{The DESC Science Roadmap is available at: \url{http://lsst-desc.org/sites/default/files/DESC_SRM_V1_0.pdf}} includes plans for realistic image-based simulations of the LSST sky.  In coordination with DESC, the inclusion of faint, large-scale LSB objects in the upcoming Data Challenge 2 catalogs and images would benefit all groups involved in testing algorithms and characterizing LSB objects.  Improvements we make may be ingested by LSST DM as a Level-3 contribution.  LSB ghosts due to reflected bright star light in the camera should also be included.   
}
~\\
\deliverables{%Deliverables over the next several years from the activities described above include the following:
~
\begin{enumerate}
\item Deliverable 1.  In coordination with the Dark Energy Science Collaboration, realistic image simulations. Faint, large-scale LSB objects should be included in DESC Data Challenge 2 image based simulations.  The level of realism in the simulations can be extended to what is physically possible, rather than limited to conventional morphological models.

**Comment by brantr** [comment]
Updated tex file from Sam.
[skysub-task_v2.tex.txt](https://github.com/brantr/ExtragalacticScienceRoadmap/files/1191632/skysub-task_v2.tex.txt)

**Comment by brantr** [comment]
@sschmidt23 , I added the section with some minor edits (it's now the new 3.6.4).  I think the sentence on "failed attempts" is a bit aggressive, but I left it as is.  Please have a look, and I'll close the issue once you agree.

**Comment by sschmidt23** [comment]
Thanks Brant.  @tonytyson wrote the vast majority of the text for this task, so I'll leave it to Tony to answer.  My suggestion would be something a little softer, like: "The current state of the art algorithms, including SDSS Photo, SExtractor, GalFit, and PyMorph, show[or maybe retain?] residual systematics in sky background routines in the LSB regime."

**Comment by tonytyson** [comment]
My point is that these algorithms fail at the ultra-low surface brightness limit appropriate for detection and photometry of extended surface brightness features of galaxies, at the depth of LSST (and its precursor deep surveys like DLS).

**Comment by brantr** [comment]
I don't disagree! I think we should adjust the word choice very slightly -- I think we'd want to encourage the developers of these algorithms to improve them. I'll do make a small change and close the ticket.

**Comment by brantr** [comment]
Now reads "Current state-of-the-art algorithms, including SDSS Photo, SExtractor, GalFit, and PyMorph, experience challenges when attempting unbiased sky estimation with deep data." Maybe too soft now ;). I'm going to close the issue.

**Comment by tonytyson** [comment]
I'd omit "state-of-the-art"
Certainly not true if SDSS Photo and SExtractor

**Comment by brantr** [comment]
Removed, thanks.
